name = "hug"
version = "0.1.1"
licences = ["Apache-2.0"]
description = "Helpful and pretty CLI messages"
repository = { type = "github", user = "brettkolodny", repo = "gleam-hug" }
gleam = ">= 0.30.0"

[javascript.deno]
allow_read = ["./gleam.toml", "./test/"]

[dependencies]
gleam_stdlib = "~> 0.30.0"
gleam_community_ansi = "~> 1.1.0"

[dev-dependencies]
gleeunit = "~> 0.10.1"
