name = "hug"
version = "1.0.2"
licences = ["Apache-2.0"]
description = "Helpful and pretty CLI messages"
repository = { type = "github", user = "brettkolodny", repo = "gleam-hug" }
gleam = ">= 1.0.0 and < 2.0.0"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
gleam_community_ansi = ">= 1.4.3 and < 2.0.0"
gleam_community_colour = ">= 2.0.1 and < 3.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.5.1 and < 2.0.0"
