name = "hug"
version = "1.0.1"
licences = ["Apache-2.0"]
description = "Helpful and pretty CLI messages"
repository = { type = "github", user = "brettkolodny", repo = "gleam-hug" }
gleam = ">= 1.0.0 and < 2.0.0"

[javascript.deno]
allow_read = ["./gleam.toml", "./test/"]

[dependencies]
gleam_stdlib = ">= 0.36.0 and < 2.0.0"
gleam_community_ansi = ">= 1.3.0 and < 2.0.0"
gleam_community_colour = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
