name = "hug"
version = "0.1.0"
description = "A Gleam project"

[javascript.deno]
allow_read = ["./gleam.toml", "./test/"]

[dependencies]
gleam_stdlib = "~> 0.26"
gleam_community_ansi = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 0.9"
gleam_erlang = "~> 0.17"
